### ISSUE TITLE
Error while starting the bot.

### ISSUE THREAD

**Issue by AmericanTrucker20** [FirezzzZ/1SHOT#12]
Hello, So I was trying to self host this bot, while trying to start it I got a SQlite error, as I dont use sqlite, could you please help me with this: 

**Error: Could not locate the bindings file. Tried:
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\compiled\12.18.2\win32\x64\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\lib\binding\node-v72-win32-x64\better_sqlite3.node
    at bindings (C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\lib\database.js:6:40)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\upadh\Desktop\Discord Bots\Softii\node_modules\better-sqlite3\lib\index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30) {
  tries: [
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\build\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\build\\Debug\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\build\\Release\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\out\\Debug\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\Debug\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\out\\Release\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\Release\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\build\\default\\better_sqlite3.node',
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\compiled\\12.18.2\\win32\\x64\\better_sqlite3.node',   
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\addon-build\\release\\install-root\\better_sqlite3.node'
,
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\addon-build\\debug\\install-root\\better_sqlite3.node',

    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\addon-build\\default\\install-root\\better_sqlite3.node'
,
    'C:\\Users\\upadh\\Desktop\\Discord Bots\\Softii\\node_modules\\better-sqlite3\\lib\\binding\\node-v72-win32-x64\\better_sqlite3.node' 
  ]
}**

**Comment by AmericanTrucker20** [comment]
I have solved this error, you can close this issue.`

**Comment by FirezzzZ** [comment]
doing `npm i` would've fixed that
